<?php

namespace App\Services\Bloom;

/**
 * Labeled training examples for the Bloom's Taxonomy logistic regression
 * classifier. Add more rows here (and re-run `php artisan bloom:train`)
 * to improve accuracy — especially with real DepEd Cavite objectives.
 *
 * ICT (Information, Communication and Technology) department objectives
 * are prioritized/overrepresented here since that's the primary client
 * subject area — covers networking, programming, databases, hardware,
 * cybersecurity, and web/app development phrasing across all six levels.
 *
 * Levels are indexed 0-5 matching BloomClassifierService::LEVELS.
 */
class BloomTrainingData
{
    public const REMEMBERING = 0;
    public const UNDERSTANDING = 1;
    public const APPLYING = 2;
    public const ANALYZING = 3;
    public const EVALUATING = 4;
    public const CREATING = 5;

    /**
     * @return array<int, array{0: string, 1: int}>
     */
    public static function samples(): array
    {
        return [
            // Remembering
            ["Students will be able to define the parts of a plant cell.", self::REMEMBERING],
            ["Students will list the presidents of the Philippines in order.", self::REMEMBERING],
            ["Students will recall the formula for the area of a circle.", self::REMEMBERING],
            ["Students will identify the capital cities of ASEAN countries.", self::REMEMBERING],
            ["Students will name the layers of the earth.", self::REMEMBERING],
            ["Students will state the law of conservation of energy.", self::REMEMBERING],
            ["Students will label the parts of a microscope.", self::REMEMBERING],
            ["Students will match vocabulary words to their definitions.", self::REMEMBERING],
            ["Students will enumerate the branches of government.", self::REMEMBERING],
            ["Students will recognize the symbols used in a circuit diagram.", self::REMEMBERING],
            ["Students will identify the different parts of speech.", self::REMEMBERING],
            ["Students will recite the Philippine national anthem correctly.", self::REMEMBERING],
            ["Students will list the provinces in Region IV-A CALABARZON.", self::REMEMBERING],
            ["Students will name the different types of rocks.", self::REMEMBERING],
            ["Students will state Newton's three laws of motion.", self::REMEMBERING],
            ["Students will recall the multiplication table up to 12.", self::REMEMBERING],
            ["Students will identify the different food groups in the food pyramid.", self::REMEMBERING],
            ["Students will label the parts of the digestive system.", self::REMEMBERING],
            ["Students will enumerate the rights of a Filipino citizen under the Constitution.", self::REMEMBERING],
            ["Students will recognize common Filipino folk songs by their titles.", self::REMEMBERING],
            ["Students will list the materials needed for a simple science experiment.", self::REMEMBERING],
            ["Students will identify the different tenses of verbs in English.", self::REMEMBERING],
            ["Students will name the municipalities of Cavite province.", self::REMEMBERING],
            ["Students will recall the steps in the water cycle in order.", self::REMEMBERING],
            ["Students will match historical events to their corresponding dates.", self::REMEMBERING],
            ["Students will state the definition of density.", self::REMEMBERING],
            ["Students will identify basic first aid supplies in a kit.", self::REMEMBERING],
            ["Students will list the safety rules to be observed in the laboratory.", self::REMEMBERING],
            ["Students will name the parts of a computer system.", self::REMEMBERING],
            ["Students will list the basic components of a balanced meal.", self::REMEMBERING],
            ["Students will identify the different Philippine bills and coins.", self::REMEMBERING],
            ["Students will recall the dates of major Philippine historical events.", self::REMEMBERING],
            ["Students will state the basic postulates of cell theory.", self::REMEMBERING],
            ["Students will identify common punctuation marks and their uses.", self::REMEMBERING],
            ["Students will list the members of the periodic table's noble gases.", self::REMEMBERING],
            ["Students will name the different types of triangles.", self::REMEMBERING],
            ["Students will recall the steps in the research process.", self::REMEMBERING],
            ["Students will identify the different values taught in Edukasyon sa Pagpapakatao.", self::REMEMBERING],
            ["Students will label the parts of a flower.", self::REMEMBERING],
            ["Students will list the basic rules of basketball.", self::REMEMBERING],
            ["Students will name the different Filipino regional dialects.", self::REMEMBERING],
            ["Students will recall the formula for calculating simple interest.", self::REMEMBERING],
            ["Students will identify the different states of matter.", self::REMEMBERING],
            ["Students will state the definition of photosynthesis.", self::REMEMBERING],
            ["Students will list the parts of a business letter.", self::REMEMBERING],
            ["Students will recognize the flags of ASEAN member countries.", self::REMEMBERING],
            ["Students will name the tools used in basic gardening.", self::REMEMBERING],
            ["Students will identify the different parts of a computer system unit.", self::REMEMBERING],
            ["Students will list the different types of computer networks.", self::REMEMBERING],
            ["Students will name the components found on a motherboard.", self::REMEMBERING],
            ["Students will recall the basic HTML tags used in web pages.", self::REMEMBERING],
            ["Students will identify common file extensions and their associated programs.", self::REMEMBERING],
            ["Students will list the different types of software licenses.", self::REMEMBERING],
            ["Students will name the layers of the OSI model.", self::REMEMBERING],
            ["Students will recall basic keyboard shortcuts used in word processing.", self::REMEMBERING],
            ["Students will identify the different input and output devices.", self::REMEMBERING],
            ["Students will list the basic data types used in programming.", self::REMEMBERING],
            ["Students will name common cybersecurity threats such as viruses and malware.", self::REMEMBERING],
            ["Students will identify the icons found on a typical desktop interface.", self::REMEMBERING],
            ["Students will recall the steps to safely shut down a computer.", self::REMEMBERING],
            ["Students will list the different types of storage devices.", self::REMEMBERING],
            ["Students will name the basic components of a database table.", self::REMEMBERING],
            ["At the end of the lesson, learners should be able to identify the parts of a URL.", self::REMEMBERING],
            ["Learners will recall the shortcut keys used in spreadsheet applications.", self::REMEMBERING],
            ["The students must be able to name the different topologies used in networking.", self::REMEMBERING],
            ["Mag-iidentify ang mga mag-aaral ng iba't ibang uri ng software.", self::REMEMBERING],
            ["Learners can list the common ports used in networking protocols.", self::REMEMBERING],
            ["The students should recall the basic syntax of a for-loop.", self::REMEMBERING],
            ["At the end of the session, learners will identify malware types such as trojans and worms.", self::REMEMBERING],
            ["Learners will define key terms related to cloud computing.", self::REMEMBERING],
            ["The students must recall the acronym HTTP and what it stands for.", self::REMEMBERING],
            ["Learners should be able to name examples of application software.", self::REMEMBERING],
            ["Mga mag-aaral ay dapat matukoy ang mga bahagi ng isang website.", self::REMEMBERING],
            ["The students will list examples of input validation errors.", self::REMEMBERING],
            ["Learners will recall the standard file naming conventions used in programming.", self::REMEMBERING],
            ["At the end of the lesson, students should identify common error messages in coding.", self::REMEMBERING],
            ["The students must list the basic Boolean operators used in logic.", self::REMEMBERING],
            ["Students will enumerate the different types of computer network topologies.", self::REMEMBERING],
            ["Learners will identify the basic input and output devices of a computer system.", self::REMEMBERING],
            ["The students should recite the preamble of the 1987 Philippine Constitution.", self::REMEMBERING],
            ["Learners will state the steps in the boot-up process of a computer.", self::REMEMBERING],
            ["At the end of the lesson, learners should list the common HTML tags used in web development.", self::REMEMBERING],
            ["Mga mag-aaral ay dapat sabihin ang mga bahagi ng CPU.", self::REMEMBERING],
            ["The students will identify the parts of a database management system.", self::REMEMBERING],
            ["Learners can name the components of a URL.", self::REMEMBERING],
            ["Students should recall the difference between RAM and ROM by definition alone.", self::REMEMBERING],
            ["The students will identify the layers of the OSI model by name.", self::REMEMBERING],

            // Understanding
            ["Students will be able to explain the water cycle in their own words.", self::UNDERSTANDING],
            ["Students will summarize the main events of the story.", self::UNDERSTANDING],
            ["Students will describe how photosynthesis works.", self::UNDERSTANDING],
            ["Students will interpret the meaning of a given graph.", self::UNDERSTANDING],
            ["Students will classify animals based on their habitats.", self::UNDERSTANDING],
            ["Students will compare and contrast mitosis and meiosis conceptually.", self::UNDERSTANDING],
            ["Students will discuss the causes of World War I.", self::UNDERSTANDING],
            ["Students will translate the given sentence into Filipino.", self::UNDERSTANDING],
            ["Students will paraphrase a paragraph from the textbook.", self::UNDERSTANDING],
            ["Students will illustrate the stages of the rock cycle.", self::UNDERSTANDING],
            ["Students will explain the significance of the EDSA People Power Revolution.", self::UNDERSTANDING],
            ["Students will describe the roles of the three branches of the Philippine government.", self::UNDERSTANDING],
            ["Students will summarize the plot of a Filipino short story.", self::UNDERSTANDING],
            ["Students will interpret data presented in a bar graph.", self::UNDERSTANDING],
            ["Students will discuss the effects of colonization on Philippine culture.", self::UNDERSTANDING],
            ["Students will explain the importance of the barangay in local governance.", self::UNDERSTANDING],
            ["Students will describe the life cycle of a butterfly.", self::UNDERSTANDING],
            ["Students will explain how the digestive system breaks down food.", self::UNDERSTANDING],
            ["Students will interpret the meaning of common Filipino idioms.", self::UNDERSTANDING],
            ["Students will summarize the key provisions of the Local Government Code.", self::UNDERSTANDING],
            ["Students will explain the difference between weather and climate.", self::UNDERSTANDING],
            ["Students will describe the process of cellular respiration.", self::UNDERSTANDING],
            ["Students will discuss the importance of proper waste segregation.", self::UNDERSTANDING],
            ["Students will explain the concept of supply and demand in simple terms.", self::UNDERSTANDING],
            ["Students will describe how vaccines help the immune system.", self::UNDERSTANDING],
            ["Students will interpret a simple map showing barangay boundaries.", self::UNDERSTANDING],
            ["Students will explain the meaning of a given proverb or salawikain.", self::UNDERSTANDING],
            ["Students will explain the difference between hardware and software.", self::UNDERSTANDING],
            ["Students will describe how data travels through a computer network.", self::UNDERSTANDING],
            ["Students will explain the purpose of an operating system.", self::UNDERSTANDING],
            ["Students will describe the function of RAM in a computer system.", self::UNDERSTANDING],
            ["Students will explain how a search engine retrieves information.", self::UNDERSTANDING],
            ["Students will describe the process of installing a software application.", self::UNDERSTANDING],
            ["Students will explain the difference between LAN and WAN.", self::UNDERSTANDING],
            ["Students will summarize the steps involved in the software development life cycle.", self::UNDERSTANDING],
            ["Students will describe how encryption protects data during transmission.", self::UNDERSTANDING],
            ["Students will explain the purpose of variables in programming.", self::UNDERSTANDING],
            ["Students will discuss the importance of backing up computer files regularly.", self::UNDERSTANDING],
            ["Students will describe how a spreadsheet formula calculates a result.", self::UNDERSTANDING],
            ["Students will explain the function of an IP address in networking.", self::UNDERSTANDING],
            ["Students will describe the difference between a database and a spreadsheet.", self::UNDERSTANDING],
            ["Students will explain the basic principles of responsible use of social media.", self::UNDERSTANDING],
            ["At the end of the lesson, learners should be able to explain how a firewall protects a network.", self::UNDERSTANDING],
            ["Learners will describe the purpose of a flowchart in programming.", self::UNDERSTANDING],
            ["The students must be able to discuss why strong passwords are important.", self::UNDERSTANDING],
            ["Ipaliliwanag ng mga mag-aaral ang kahalagahan ng data privacy.", self::UNDERSTANDING],
            ["Learners can summarize the steps of the input-process-output model.", self::UNDERSTANDING],
            ["The students should explain the difference between compiling and interpreting code.", self::UNDERSTANDING],
            ["At the end of the session, learners will describe how cookies are used by websites.", self::UNDERSTANDING],
            ["Learners will discuss the advantages of using cloud storage over local storage.", self::UNDERSTANDING],
            ["The students must explain the role of a server in a client-server architecture.", self::UNDERSTANDING],
            ["Learners should be able to describe the function of a router in a home network.", self::UNDERSTANDING],
            ["Mga mag-aaral ay dapat maipaliwanag ang proseso ng pag-debug ng programa.", self::UNDERSTANDING],
            ["The students will summarize the main features of an operating system.", self::UNDERSTANDING],
            ["Learners will explain why software updates are necessary for security.", self::UNDERSTANDING],
            ["At the end of the lesson, students should discuss the ethical use of AI tools.", self::UNDERSTANDING],
            ["The students must describe the difference between a bug and a feature in software.", self::UNDERSTANDING],
            ["Students will explain the difference between LAN and WAN networks.", self::UNDERSTANDING],
            ["Learners can summarize the causes of the Philippine Revolution of 1896.", self::UNDERSTANDING],
            ["Students will describe how a relational database enforces data integrity.", self::UNDERSTANDING],
            ["Learners can explain the purpose of variables and constants in programming.", self::UNDERSTANDING],
            ["Students will interpret a simple flowchart representing a decision structure.", self::UNDERSTANDING],
            ["Mga mag-aaral ay dapat ipaliwanag ang kahalagahan ng OSI model sa networking.", self::UNDERSTANDING],
            ["Students will explain how normalization reduces data redundancy in a database.", self::UNDERSTANDING],
            ["Learners can describe the function of an operating system's task scheduler.", self::UNDERSTANDING],
            ["Students will paraphrase the key provisions of the Data Privacy Act of 2012.", self::UNDERSTANDING],
            ["Learners can explain the concept of object-oriented programming in their own words.", self::UNDERSTANDING],

            // Applying
            ["Students will solve quadratic equations using the quadratic formula.", self::APPLYING],
            ["Students will use the scientific method to conduct an experiment.", self::APPLYING],
            ["Students will demonstrate proper handwashing technique.", self::APPLYING],
            ["Students will apply grammar rules to correct sentences.", self::APPLYING],
            ["Students will calculate the area of irregular shapes.", self::APPLYING],
            ["Students will implement a simple sorting algorithm in code.", self::APPLYING],
            ["Students will construct a budget plan using given data.", self::APPLYING],
            ["Students will operate a Bunsen burner safely during the lab.", self::APPLYING],
            ["Students will practice long division using multi-digit numbers.", self::APPLYING],
            ["Students will execute the steps of a dance routine correctly.", self::APPLYING],
            ["Students will use a map to determine the distance between two towns.", self::APPLYING],
            ["Students will apply the Pythagorean theorem to solve real-world problems.", self::APPLYING],
            ["Students will conduct a simple titration experiment following procedure.", self::APPLYING],
            ["Students will write a formal letter following proper business format.", self::APPLYING],
            ["Students will compute the perimeter and area of a barangay plaza.", self::APPLYING],
            ["Students will apply proper subject-verb agreement in writing sentences.", self::APPLYING],
            ["Students will demonstrate correct CPR technique on a training mannequin.", self::APPLYING],
            ["Students will prepare a simple Filipino dish following a given recipe.", self::APPLYING],
            ["Students will use Microsoft Excel to compute basic statistical measures.", self::APPLYING],
            ["Students will apply the rules of divisibility to solve number problems.", self::APPLYING],
            ["Students will operate basic carpentry tools safely during a TLE activity.", self::APPLYING],
            ["Students will use appropriate measuring instruments to record rainfall data.", self::APPLYING],
            ["Students will apply the steps of the scientific method to a class investigation.", self::APPLYING],
            ["Students will demonstrate proper posture and form during a badminton serve.", self::APPLYING],
            ["Students will use a rubric to compute a peer's project score.", self::APPLYING],
            ["Students will convert given units of measurement from metric to English system.", self::APPLYING],
            ["Students will create a simple webpage using HTML and CSS.", self::APPLYING],
            ["Students will use spreadsheet formulas to compute a class average.", self::APPLYING],
            ["Students will write a basic program to calculate the sum of two numbers.", self::APPLYING],
            ["Students will set up a local area network using given equipment.", self::APPLYING],
            ["Students will apply proper formatting techniques in a word processing document.", self::APPLYING],
            ["Students will use a database management system to insert new records.", self::APPLYING],
            ["Students will troubleshoot common computer hardware issues following a checklist.", self::APPLYING],
            ["Students will apply basic debugging techniques to fix errors in code.", self::APPLYING],
            ["Students will use presentation software to create a multimedia slideshow.", self::APPLYING],
            ["Students will configure basic network settings on a router.", self::APPLYING],
            ["Students will apply loops and conditional statements in a sample program.", self::APPLYING],
            ["Students will use image editing software to resize and crop a photo.", self::APPLYING],
            ["Students will apply password security best practices when creating an account.", self::APPLYING],
            ["Students will use version control commands to commit changes to a repository.", self::APPLYING],
            ["Students will install and configure a basic antivirus program.", self::APPLYING],
            ["At the end of the lesson, learners should be able to build a basic contact form using HTML.", self::APPLYING],
            ["Learners will use conditional logic to validate user input in a program.", self::APPLYING],
            ["The students must apply CSS styling to improve a webpage's layout.", self::APPLYING],
            ["Gagamitin ng mga mag-aaral ang spreadsheet upang kalkulahin ang kabuuang gastos.", self::APPLYING],
            ["Learners can configure a firewall rule to block unauthorized access.", self::APPLYING],
            ["The students should write a SQL query to retrieve specific records from a table.", self::APPLYING],
            ["At the end of the session, learners will apply proper indentation when writing code.", self::APPLYING],
            ["Learners will set up an email account following proper security settings.", self::APPLYING],
            ["The students must use a flowchart to plan the logic of a simple program.", self::APPLYING],
            ["Learners should be able to apply file compression techniques to reduce file size.", self::APPLYING],
            ["Mga mag-aaral ay dapat magamit ang mga tool sa pag-edit ng litrato.", self::APPLYING],
            ["The students will implement a login form with basic input validation.", self::APPLYING],
            ["Learners will apply naming conventions when creating variables in code.", self::APPLYING],
            ["At the end of the lesson, students should demonstrate how to back up files to cloud storage.", self::APPLYING],
            ["The students must use a project management tool to track team tasks.", self::APPLYING],
            ["Students will configure a basic IP addressing scheme for a small office network.", self::APPLYING],
            ["Learners can use loops and conditionals to solve a given programming problem.", self::APPLYING],
            ["Students will demonstrate how to create a normalized database schema from given requirements.", self::APPLYING],
            ["Learners will apply CSS styling rules to format a webpage layout.", self::APPLYING],
            ["Students can install and configure a local web server for testing applications.", self::APPLYING],
            ["Mga mag-aaral ay dapat gumamit ng SQL query para kumuha ng partikular na record.", self::APPLYING],
            ["Students will apply the steps of the software development life cycle to a mini project.", self::APPLYING],
            ["Learners can troubleshoot a computer that fails to connect to the internet.", self::APPLYING],
            ["Students will demonstrate proper crimping of a UTP cable for network connections.", self::APPLYING],
            ["Learners will apply Boolean logic to construct a database search query.", self::APPLYING],

            // Analyzing
            ["Students will differentiate between mitosis and meiosis.", self::ANALYZING],
            ["Students will analyze the causes and effects of climate change.", self::ANALYZING],
            ["Students will compare the themes of two literary works.", self::ANALYZING],
            ["Students will examine the structure of a persuasive essay.", self::ANALYZING],
            ["Students will categorize rocks based on their formation process.", self::ANALYZING],
            ["Students will distinguish between fact and opinion in an article.", self::ANALYZING],
            ["Students will investigate the relationship between supply and demand.", self::ANALYZING],
            ["Students will deconstruct an argument to identify its assumptions.", self::ANALYZING],
            ["Students will break down a chemical reaction into its component steps.", self::ANALYZING],
            ["Students will contrast two economic systems based on given criteria.", self::ANALYZING],
            ["Students will analyze the impact of Spanish colonization on Filipino identity.", self::ANALYZING],
            ["Students will compare the leadership styles of two Philippine presidents.", self::ANALYZING],
            ["Students will examine primary sources to determine bias in historical accounts.", self::ANALYZING],
            ["Students will differentiate between renewable and non-renewable energy sources.", self::ANALYZING],
            ["Students will analyze the structure of a persuasive speech for rhetorical devices.", self::ANALYZING],
            ["Students will categorize plants based on their reproductive structures.", self::ANALYZING],
            ["Students will examine survey data to identify trends in community needs.", self::ANALYZING],
            ["Students will distinguish between cause and effect in a historical event.", self::ANALYZING],
            ["Students will analyze the nutritional content of common Filipino meals.", self::ANALYZING],
            ["Students will compare the economic policies of two ASEAN countries.", self::ANALYZING],
            ["Students will investigate factors contributing to flooding in low-lying barangays.", self::ANALYZING],
            ["Students will deconstruct a news article to identify fact from opinion.", self::ANALYZING],
            ["Students will analyze character motivations in a Filipino novel.", self::ANALYZING],
            ["Students will examine a budget proposal to identify areas of overspending.", self::ANALYZING],
            ["Students will differentiate the types of sentences based on structure and function.", self::ANALYZING],
            ["Students will analyze a given algorithm to determine its time complexity.", self::ANALYZING],
            ["Students will compare the features of two different operating systems.", self::ANALYZING],
            ["Students will examine a network diagram to identify potential bottlenecks.", self::ANALYZING],
            ["Students will differentiate between structured and unstructured data.", self::ANALYZING],
            ["Students will analyze a piece of code to identify logical errors.", self::ANALYZING],
            ["Students will compare the security features of different web browsers.", self::ANALYZING],
            ["Students will examine system logs to identify unauthorized access attempts.", self::ANALYZING],
            ["Students will differentiate between relational and non-relational databases.", self::ANALYZING],
            ["Students will analyze user requirements to determine appropriate software features.", self::ANALYZING],
            ["Students will compare wired and wireless network technologies based on given criteria.", self::ANALYZING],
            ["Students will investigate the causes of a network outage using diagnostic tools.", self::ANALYZING],
            ["Students will examine a website's design to identify usability issues.", self::ANALYZING],
            ["Students will differentiate between phishing and legitimate email messages.", self::ANALYZING],
            ["Students will analyze a database schema to identify normalization issues.", self::ANALYZING],
            ["Students will compare the performance of two different sorting algorithms.", self::ANALYZING],
            ["At the end of the lesson, learners should be able to analyze error logs to identify the source of a bug.", self::ANALYZING],
            ["Learners will compare the efficiency of two different programming approaches.", self::ANALYZING],
            ["The students must examine a system's architecture to identify single points of failure.", self::ANALYZING],
            ["Susuriin ng mga mag-aaral ang mga panganib sa cybersecurity ng isang network.", self::ANALYZING],
            ["Learners can differentiate between synchronous and asynchronous programming.", self::ANALYZING],
            ["The students should analyze user feedback to identify common app usability problems.", self::ANALYZING],
            ["At the end of the session, learners will compare the trade-offs of different database indexing strategies.", self::ANALYZING],
            ["Learners will investigate why a given webpage loads slowly.", self::ANALYZING],
            ["The students must distinguish between client-side and server-side validation.", self::ANALYZING],
            ["Learners should be able to examine a codebase to identify redundant functions.", self::ANALYZING],
            ["Mga mag-aaral ay dapat suriin ang pagkakaiba ng mga uri ng cyber attacks.", self::ANALYZING],
            ["The students will analyze traffic patterns to detect a possible DDoS attack.", self::ANALYZING],
            ["Learners will compare the scalability of monolithic versus microservices architecture.", self::ANALYZING],
            ["At the end of the lesson, students should differentiate between software bugs and hardware failures.", self::ANALYZING],
            ["The students must examine test results to identify which module is failing.", self::ANALYZING],
            ["Students will differentiate between symmetric and asymmetric encryption algorithms.", self::ANALYZING],
            ["Learners can analyze a given network diagram to identify potential points of failure.", self::ANALYZING],
            ["Students will compare the efficiency of different sorting algorithms given a dataset.", self::ANALYZING],
            ["Learners can examine a piece of code to identify logical errors causing incorrect output.", self::ANALYZING],
            ["Students will break down a system's requirements into functional and non-functional components.", self::ANALYZING],
            ["Mga mag-aaral ay dapat ihambing ang bentahe at disbentahe ng waterfall at agile methodology.", self::ANALYZING],
            ["Students will analyze the trade-offs between relational and NoSQL databases for a given use case.", self::ANALYZING],
            ["Learners can categorize cybersecurity threats based on their attack vectors.", self::ANALYZING],
            ["Students will examine a company's IT infrastructure to identify security vulnerabilities.", self::ANALYZING],
            ["Learners can compare the strengths and weaknesses of waterfall versus agile methodologies.", self::ANALYZING],

            // Evaluating
            ["Students will evaluate the effectiveness of a given marketing strategy.", self::EVALUATING],
            ["Students will critique a peer's essay based on a rubric.", self::EVALUATING],
            ["Students will justify their position on a controversial issue.", self::EVALUATING],
            ["Students will assess the validity of a scientific claim.", self::EVALUATING],
            ["Students will judge the credibility of different historical sources.", self::EVALUATING],
            ["Students will defend a chosen solution to an environmental problem.", self::EVALUATING],
            ["Students will recommend improvements to an existing school policy.", self::EVALUATING],
            ["Students will appraise the quality of a research study's methodology.", self::EVALUATING],
            ["Students will rank the proposed solutions from most to least effective.", self::EVALUATING],
            ["Students will argue for or against a given ethical dilemma.", self::EVALUATING],
            ["Students will evaluate the effectiveness of the barangay's disaster preparedness plan.", self::EVALUATING],
            ["Students will assess the reliability of online sources used in research.", self::EVALUATING],
            ["Students will critique a classmate's oral presentation using a scoring rubric.", self::EVALUATING],
            ["Students will judge which of two proposed solutions best addresses flooding.", self::EVALUATING],
            ["Students will justify their stance on the use of plastic in packaging.", self::EVALUATING],
            ["Students will evaluate the environmental impact of a proposed local project.", self::EVALUATING],
            ["Students will assess the strengths and weaknesses of a persuasive essay.", self::EVALUATING],
            ["Students will critique the fairness of a given classroom policy.", self::EVALUATING],
            ["Students will judge the accuracy of a historical documentary's claims.", self::EVALUATING],
            ["Students will evaluate the nutritional value of a school canteen menu.", self::EVALUATING],
            ["Students will defend their chosen method for solving a math problem.", self::EVALUATING],
            ["Students will assess the effectiveness of a public health campaign.", self::EVALUATING],
            ["Students will rank possible solutions to traffic congestion in the town center.", self::EVALUATING],
            ["Students will evaluate a peer's research paper for methodological soundness.", self::EVALUATING],
            ["Students will argue whether a historical figure's actions were justified.", self::EVALUATING],
            ["Students will evaluate the effectiveness of a given cybersecurity policy.", self::EVALUATING],
            ["Students will assess the usability of a mobile application interface.", self::EVALUATING],
            ["Students will critique a classmate's code based on programming best practices.", self::EVALUATING],
            ["Students will judge which programming language best fits a given project.", self::EVALUATING],
            ["Students will justify their choice of database structure for a given system.", self::EVALUATING],
            ["Students will evaluate the reliability of a proposed network security plan.", self::EVALUATING],
            ["Students will assess the quality of a website based on accessibility standards.", self::EVALUATING],
            ["Students will critique the design of a user interface prototype.", self::EVALUATING],
            ["Students will judge the effectiveness of a given data backup strategy.", self::EVALUATING],
            ["Students will evaluate the pros and cons of cloud-based versus local storage.", self::EVALUATING],
            ["Students will assess the ethical implications of a proposed data collection system.", self::EVALUATING],
            ["Students will defend their chosen software architecture for a class project.", self::EVALUATING],
            ["Students will rank different project management tools based on team needs.", self::EVALUATING],
            ["Students will evaluate a peer's system documentation for completeness and clarity.", self::EVALUATING],
            ["Students will judge whether a given app complies with data privacy requirements.", self::EVALUATING],
            ["At the end of the lesson, learners should be able to evaluate whether a given app meets accessibility standards.", self::EVALUATING],
            ["Learners will assess the security risks of storing passwords in plain text.", self::EVALUATING],
            ["The students must judge which cloud provider best fits a startup's needs.", self::EVALUATING],
            ["Susuriin at bibigyang-halaga ng mga mag-aaral ang kahusayan ng isang website design.", self::EVALUATING],
            ["Learners can critique a peer's code review comments for constructiveness.", self::EVALUATING],
            ["The students should evaluate the trade-offs between speed and security in an app design.", self::EVALUATING],
            ["At the end of the session, learners will justify their choice of testing framework for a project.", self::EVALUATING],
            ["Learners will assess whether a proposed system meets the client's requirements.", self::EVALUATING],
            ["The students must evaluate the effectiveness of a given incident response plan.", self::EVALUATING],
            ["Learners should be able to judge the maintainability of a given codebase.", self::EVALUATING],
            ["Mga mag-aaral ay dapat husgahan ang kalidad ng isang mobile application.", self::EVALUATING],
            ["The students will critique the accessibility of a website for users with disabilities.", self::EVALUATING],
            ["Learners will evaluate whether an algorithm's output is accurate and efficient.", self::EVALUATING],
            ["At the end of the lesson, students should assess the reliability of a third-party API.", self::EVALUATING],
            ["The students must judge which UI design better serves the target users.", self::EVALUATING],
            ["Students will assess the effectiveness of a proposed disaster recovery plan for a school's IT system.", self::EVALUATING],
            ["Learners can judge whether a given algorithm meets the time complexity requirements of a problem.", self::EVALUATING],
            ["Students will critique a classmate's database design based on normalization principles.", self::EVALUATING],
            ["Learners can evaluate the reliability of an open-source library before including it in a project.", self::EVALUATING],
            ["Students will justify the choice of a particular programming language for a given system.", self::EVALUATING],
            ["Mga mag-aaral ay dapat suriin ang kapaki-pakinabang ng isang mobile application interface.", self::EVALUATING],
            ["Students will determine whether a proposed network topology adequately meets an office's scalability needs.", self::EVALUATING],
            ["Learners can evaluate the ethical implications of collecting user data without explicit consent.", self::EVALUATING],
            ["Students will assess the security risks of storing passwords in plain text versus hashed formats.", self::EVALUATING],
            ["Learners can recommend, with justification, the best cloud hosting provider for a small business.", self::EVALUATING],
            ["Students will weigh the pros and cons of outsourcing IT support versus hiring an in-house team.", self::EVALUATING],
            ["Learners can appraise the usability of a mobile application's user interface against accessibility standards.", self::EVALUATING],
            ["Students will evaluate a vendor's proposal against the school division's technical requirements.", self::EVALUATING],
            ["Learners can judge the credibility of a source before citing it in a research paper.", self::EVALUATING],

            // Creating
            ["Students will design an original experiment to test a hypothesis.", self::CREATING],
            ["Students will create a multimedia presentation about renewable energy.", self::CREATING],
            ["Students will compose an original short story using given vocabulary.", self::CREATING],
            ["Students will develop a business plan for a school enterprise.", self::CREATING],
            ["Students will construct a working model of a simple machine.", self::CREATING],
            ["Students will formulate a new theory to explain the observed data.", self::CREATING],
            ["Students will produce an original artwork inspired by a historical era.", self::CREATING],
            ["Students will devise a plan to reduce plastic waste in the community.", self::CREATING],
            ["Students will invent a new tool to solve an everyday problem.", self::CREATING],
            ["Students will draft a proposal for a new school program.", self::CREATING],
            ["Students will design a community awareness campaign on proper waste segregation.", self::CREATING],
            ["Students will create an original mobile app prototype to address a school need.", self::CREATING],
            ["Students will compose an original kundiman-style song.", self::CREATING],
            ["Students will develop a disaster preparedness plan for their barangay.", self::CREATING],
            ["Students will design an infographic explaining climate change to younger students.", self::CREATING],
            ["Students will create a business plan for a small sari-sari store enterprise.", self::CREATING],
            ["Students will construct a scale model of a sustainable barangay layout.", self::CREATING],
            ["Students will formulate an original research question for a science investigation.", self::CREATING],
            ["Students will write and perform an original skit about bullying prevention.", self::CREATING],
            ["Students will design a garden layout that maximizes limited barangay space.", self::CREATING],
            ["Students will produce a short documentary film about local Cavite history.", self::CREATING],
            ["Students will devise an original board game that teaches Philippine history.", self::CREATING],
            ["Students will create a proposal for improving the school's recycling program.", self::CREATING],
            ["Students will compose an original poem reflecting Filipino values.", self::CREATING],
            ["Students will design a functional prototype using recycled materials.", self::CREATING],
            ["Students will design and develop a functional mobile application prototype.", self::CREATING],
            ["Students will create an original database system for a small business.", self::CREATING],
            ["Students will develop a website that showcases a school's ICT programs.", self::CREATING],
            ["Students will design a network infrastructure plan for a small office.", self::CREATING],
            ["Students will build an original chatbot to answer frequently asked questions.", self::CREATING],
            ["Students will formulate a cybersecurity plan for protecting school records.", self::CREATING],
            ["Students will create a software prototype to automate a manual school process.", self::CREATING],
            ["Students will design a user interface for a proposed inventory system.", self::CREATING],
            ["Students will develop an original game using a beginner programming platform.", self::CREATING],
            ["Students will construct a capstone project integrating hardware and software components.", self::CREATING],
            ["Students will devise a data migration plan for transferring records to a new system.", self::CREATING],
            ["Students will create a technical documentation manual for a developed system.", self::CREATING],
            ["Students will design an e-commerce platform prototype for a local enterprise.", self::CREATING],
            ["Students will formulate an original algorithm to solve a given computational problem.", self::CREATING],
            ["Students will develop a training module for onboarding new ICT staff.", self::CREATING],
            ["At the end of the lesson, learners should be able to design and deploy a functional web application.", self::CREATING],
            ["Learners will develop an original mobile app to solve a community problem.", self::CREATING],
            ["The students must build a working prototype of an IoT-based monitoring system.", self::CREATING],
            ["Gagawa ang mga mag-aaral ng orihinal na website para sa isang lokal na negosyo.", self::CREATING],
            ["Learners can construct a REST API to serve data to a front-end application.", self::CREATING],
            ["The students should design a database schema for a school library system.", self::CREATING],
            ["At the end of the session, learners will formulate a testing plan for a new software feature.", self::CREATING],
            ["Learners will create an automated script to streamline a repetitive task.", self::CREATING],
            ["The students must devise a disaster recovery plan for a school's IT infrastructure.", self::CREATING],
            ["Learners should be able to develop a machine learning model to classify simple data.", self::CREATING],
            ["Mga mag-aaral ay dapat lumikha ng sariling sistema para sa pag-track ng inventory.", self::CREATING],
            ["The students will design a responsive website that works across different devices.", self::CREATING],
            ["Learners will construct a network topology diagram for a proposed office setup.", self::CREATING],
            ["At the end of the lesson, students should build an original browser extension to solve a specific need.", self::CREATING],
            ["The students must formulate a complete software requirements specification document.", self::CREATING],
            ["Students will design and implement a fully functional inventory management system.", self::CREATING],
            ["Learners can develop an original mobile application to address a community problem.", self::CREATING],
            ["Students will formulate a comprehensive cybersecurity policy for a simulated organization.", self::CREATING],
            ["Learners can construct a normalized database schema from scratch for a hospital management system.", self::CREATING],
            ["Students will design an original network architecture for a multi-branch school system.", self::CREATING],
            ["Mga mag-aaral ay dapat lumikha ng isang solusyon sa problema ng optimization gamit ang bagong algorithm.", self::CREATING],
            ["Students will build a working prototype of an IoT-based attendance monitoring system.", self::CREATING],
            ["Learners can devise a testing plan to validate a newly developed software system.", self::CREATING],
            ["Students will create an original capstone proposal integrating machine learning into a DepEd process.", self::CREATING],
            ["Learners can develop a data migration strategy for moving a legacy system to the cloud.", self::CREATING],
        ];
    }
}